### ISSUE TITLE
Edge case: multiplying a negative number with 0 should return -0

### ISSUE THREAD

**Issue by tovine** [pulp-platform/fpu#5]
The FMAC seems to handle this correctly, but the regular multiplier doesn't.
This is a minor bug limited to (what I suspect is a special case in) sign handling, but still violates the behavior expected by the RISC-V ISA spec (see also Andrew's answer here: https://github.com/riscv/riscv-tests/issues/127#issuecomment-383655088).

I can probably take a look at it and submit a PR if you want, just let me know. 😃

**Comment by stmach** [comment]
You're right!
If you have time to submit a PR for this one, your contribution would be appreciated.
